#!/usr/bin/env bash
# Post-install configuration. Run with sudo AFTER scripts/install.sh.
#
#   sudo bash scripts/configure.sh
#
# Detects what's available on the host and writes /etc/ritsu/env accordingly:
#
#   Tailscale + `tailscale serve` available (recommended):
#     - ritsu binds 127.0.0.1 only (not directly reachable from tailnet)
#     - tailscale serve fronts both ports with HTTPS on dedicated ports
#       (admin → :8443, mcp → :9443)
#     - URLs become https://<host>.<tailnet>.ts.net:8443/admin etc — auto
#       cert, browser-clean, password-manager friendly
#
#   Tailscale present but no serve (older tailscale or opted out):
#     - ritsu binds to the Tailscale IP directly, plain HTTP
#     - reachable from any tailnet device at http://<host>:7334/admin
#
#   No Tailscale:
#     - ritsu binds 127.0.0.1, SSH-tunnel from clients
#
# Plus: prints the admin token banner on first run, installs the
# /usr/local/bin/update-ritsu shortcut, restarts the service, smoke-tests.
#
# Idempotent — re-run any time to roll detection forward.
#
# Override:  RITSU_NO_TAILSCALE_SERVE=1 sudo bash configure.sh
#            forces the "bind to Tailscale IP, no serve" path.

set -euo pipefail

[[ $EUID -eq 0 ]] || { echo "must be run with sudo" >&2; exit 2; }

bold() { printf '\033[1m%s\033[0m\n' "$*"; }
note() { printf '\033[2m  %s\033[0m\n' "$*"; }
warn() { printf '\033[33m  ! %s\033[0m\n' "$*"; }

ENV_FILE=/etc/ritsu/env
SERVICE_USER=ritsu
SERVICE_NAME=ritsu.service
ADMIN_SERVE_PORT=8443
MCP_SERVE_PORT=9443

bold "==> Detect environment"

TAILSCALE_IP=""
TS_DNS=""
USE_TS_SERVE=false

if command -v tailscale >/dev/null 2>&1; then
  TAILSCALE_IP="$(tailscale ip -4 2>/dev/null | head -1 || true)"
  if [[ -n "${TAILSCALE_IP}" ]]; then
    note "Tailscale: ${TAILSCALE_IP}"
    # Magic-DNS hostname (e.g. your-host.your-tailnet.ts.net) for URL printing.
    TS_DNS="$(tailscale status --json 2>/dev/null \
      | python3 -c 'import json,sys; d=json.load(sys.stdin); print((d.get("Self",{}).get("DNSName","") or "").rstrip("."))' \
      2>/dev/null || true)"
    if [[ -n "${TS_DNS}" ]]; then
      note "magic-dns: ${TS_DNS}"
    fi
    # `tailscale serve` is available on Tailscale 1.42+ (rolled out 2023).
    if [[ "${RITSU_NO_TAILSCALE_SERVE:-}" != "1" ]] && tailscale serve status >/dev/null 2>&1; then
      USE_TS_SERVE=true
      note "tailscale serve available — will front ritsu with HTTPS"
    fi
  fi
fi

if ${USE_TS_SERVE}; then
  MCP_HOST=127.0.0.1
  ADMIN_HOST=127.0.0.1
  note "ritsu will bind 127.0.0.1 only; tailscale serve does the public-facing piece"
elif [[ -n "${TAILSCALE_IP}" ]]; then
  MCP_HOST="${TAILSCALE_IP}"
  ADMIN_HOST="${TAILSCALE_IP}"
  note "tailscale serve unavailable — binding ritsu to Tailscale IP directly (HTTP)"
else
  MCP_HOST=127.0.0.1
  ADMIN_HOST=127.0.0.1
  note "no Tailscale — binding 127.0.0.1 (use SSH tunnel from clients)"
fi

bold "==> Write ${ENV_FILE}"
# If Tailscale Serve is fronting MCP, the SDK's DNS-rebinding protection
# (auto-enabled when bound to loopback) rejects the Host: <ts-name> that
# the proxy forwards. Allow it explicitly.
ALLOWED_HOSTS_LINE=""
PUBLIC_URL_LINE=""
if ${USE_TS_SERVE} && [[ -n "${TS_DNS}" ]]; then
  ALLOWED_HOSTS_LINE="RITSU_ALLOWED_HOSTS=${TS_DNS}"
  # OAuth metadata documents use this as the issuer + canonical resource
  # origin. Tokens are bound to ${PUBLIC_URL}/mcp (RFC 8707 audience).
  # Required for MCP-spec clients (claude.ai web "Add custom connector").
  PUBLIC_URL_LINE="RITSU_PUBLIC_URL=https://${TS_DNS}:${MCP_SERVE_PORT}"
fi
install -o "${SERVICE_USER}" -g "${SERVICE_USER}" -m 600 /dev/stdin "${ENV_FILE}" <<EOF
# Generated by scripts/configure.sh. Re-run to refresh.
# NOTE: dotenv does not strip inline comments — keep them on their own line.

PORT=7333
MCP_HOST=${MCP_HOST}
# prod default; mint a token in the admin UI to actually use it
MCP_REQUIRE_AUTH=on

ADMIN_PORT=7334
# admin requires a bearer token (Phase 7) — safe to expose on the tailnet.
# Set to 127.0.0.1 if you'd rather SSH-tunnel to manage.
ADMIN_HOST=${ADMIN_HOST}

# Extra hostnames the MCP server accepts in the Host header
# (needed when a reverse proxy like Tailscale Serve forwards a public name).
${ALLOWED_HOSTS_LINE}

# Canonical public origin (no trailing slash). Required for OAuth-spec
# clients (claude.ai web, Claude Desktop Connectors). Without this,
# header-based clients (Claude Code CLI, curl) still work via rt_* tokens.
${PUBLIC_URL_LINE}

DB_PATH=/opt/ritsu/data/ritsu.db
LOG_LEVEL=info

# Bootstrap admin token (mode 0600 owned by ritsu). The server writes this
# path on first start; `ritsu admin-token show` reads it.
RITSU_ADMIN_TOKEN_FILE=/opt/ritsu/data/.admin-token
EOF
note "ok"

# Note: extra filesystem paths the systemd sandbox should let ritsu write to
# are managed via the `ritsu path` subcommand (installed below). Run e.g.
#   sudo ritsu path add /mnt/agent-sync
# to expose a shared mount; the CLI writes /etc/ritsu/sandbox-paths.list,
# regenerates the drop-in, daemon-reloads and restarts.

bold "==> Install /usr/local/bin/ritsu (operator CLI)"
# Symlink the built CLI into PATH. Re-pointed each configure run so update-ritsu
# pushes a new dist/cli.js and the symlink picks it up automatically.
if [[ -f /opt/ritsu/dist/cli.js ]]; then
  install -o root -g root -m 755 /dev/stdin /usr/local/bin/ritsu <<'SHIM'
#!/usr/bin/env bash
# Operator CLI. Wraps node so the dist/cli.js shebang isn't required to
# resolve the right node binary on hosts with multiple versions installed.
exec /usr/bin/node /opt/ritsu/dist/cli.js "$@"
SHIM
  note "ok — run 'ritsu help' to see subcommands"
else
  warn "dist/cli.js not found — run 'npm run build' before re-running configure"
fi

bold "==> Install /usr/local/bin/update-ritsu (legacy alias)"
install -o root -g root -m 755 /dev/stdin /usr/local/bin/update-ritsu <<'SHIM'
#!/usr/bin/env bash
# Legacy shortcut. New: `sudo update-ritsu` still works, OR use:
#   ritsu service restart       to bounce without rebuilding
#   sudo update-ritsu           to pull + rebuild + restart
exec sudo bash /opt/ritsu/scripts/update.sh "$@"
SHIM
note "ok"

bold "==> Restart"
systemctl restart "${SERVICE_NAME}"
# Give the service a beat to bootstrap the admin token (first boot only).
sleep 2
systemctl --no-pager status "${SERVICE_NAME}" | head -8

if ${USE_TS_SERVE}; then
  bold "==> Configure tailscale serve"
  # Idempotent: --bg replaces any existing serve on the same port.
  # Coexists with anything else already served on / or other ports.
  tailscale serve --bg --https="${ADMIN_SERVE_PORT}" "http://127.0.0.1:7334" >/dev/null
  note "admin: https port ${ADMIN_SERVE_PORT} → 127.0.0.1:7334"
  tailscale serve --bg --https="${MCP_SERVE_PORT}"   "http://127.0.0.1:7333" >/dev/null
  note "mcp:   https port ${MCP_SERVE_PORT} → 127.0.0.1:7333"
fi

bold "==> Smoke test"
note "admin /healthz: $(curl -s "http://${ADMIN_HOST}:7334/healthz" || echo failed)"
note "admin /readyz:  $(curl -s "http://${ADMIN_HOST}:7334/readyz"  || echo failed)"
note "admin /version: $(curl -s "http://${ADMIN_HOST}:7334/version" || echo failed)"

# Print URLs the operator should actually use.
bold "==> URLs"
if ${USE_TS_SERVE} && [[ -n "${TS_DNS}" ]]; then
  note "admin UI:  https://${TS_DNS}:${ADMIN_SERVE_PORT}/admin"
  note "MCP:       https://${TS_DNS}:${MCP_SERVE_PORT}/mcp"
  note "OAuth PRM: https://${TS_DNS}:${MCP_SERVE_PORT}/.well-known/oauth-protected-resource"
elif [[ -n "${TAILSCALE_IP}" ]]; then
  note "admin UI:  http://${TAILSCALE_IP}:7334/admin    (or http://<host>:7334/admin via magic-dns)"
  note "MCP:       http://${TAILSCALE_IP}:7333/mcp"
else
  note "admin UI:  http://localhost:7334/admin   (SSH-tunnel from client)"
  note "MCP:       http://localhost:7333/mcp"
fi

# Admin token: bootstrapped by the server on first boot; lives at
# /opt/ritsu/data/.admin-token (mode 0600 owned by ritsu). Print it
# loudly the first time configure runs after a fresh install.
ADMIN_TOKEN_FILE=/opt/ritsu/data/.admin-token
if [[ -f "${ADMIN_TOKEN_FILE}" ]]; then
  ADMIN_TOKEN="$(cat "${ADMIN_TOKEN_FILE}")"
  echo
  printf '\033[1;33m'
  echo '════════════════════════════════════════════════════════════════════'
  echo '                       ADMIN TOKEN'
  echo
  echo "  ${ADMIN_TOKEN}"
  echo
  echo '  Required to reach /admin/* (UI + CRUD + Tokens + Logs).'
  echo "  Stored at ${ADMIN_TOKEN_FILE} (mode 0600 owned by ritsu)."
  echo '  Re-read any time with:  sudo cat '"${ADMIN_TOKEN_FILE}"
  echo '  Paste into the admin UI when prompted, OR send as'
  echo '  X-Ritsu-Admin-Token / Authorization: Bearer header on /admin/* calls.'
  echo '════════════════════════════════════════════════════════════════════'
  printf '\033[0m'
fi

bold "==> Done"
note "future updates (from anywhere with SSH):  sudo update-ritsu"
if [[ ! -f "/home/${SERVICE_USER}/.claude/.credentials.json" ]]; then
  warn ""
  warn "Claude CLI session not present at /home/${SERVICE_USER}/.claude/.credentials.json"
  warn "claude-direct dispatcher won't work until you run:"
  warn "  which claude || sudo npm install -g @anthropic-ai/claude-code"
  warn "  sudo -u ${SERVICE_USER} -H claude login"
fi
