/**
 * `ritsu path` — manage ReadWritePaths the systemd sandbox lets ritsu write.
 *
 * Source of truth is /etc/ritsu/sandbox-paths.list (one absolute path per
 * line, # comments). The drop-in at
 * /etc/systemd/system/ritsu.service.d/sandbox-paths.conf is mechanically
 * derived from that list; editing it by hand will get overwritten.
 *
 * Adding a path = write list, regenerate drop-in, daemon-reload, restart.
 * Removing = same minus the path. List = print current list.
 */
import { readFileSync, writeFileSync, existsSync, statSync, mkdirSync } from 'node:fs';
import { spawnSync } from '../../util/safe-spawn.js';
import type { Command, CommandContext } from '../registry.js';
import { daemonReload, restartService, mountUnitFor, SERVICE_NAME } from '../systemd.js';
import { stripTrailingSlashes } from '../../util/path-utils.js';

const LIST_FILE = '/etc/ritsu/sandbox-paths.list';
const DROPIN_DIR = '/etc/systemd/system/ritsu.service.d';
const DROPIN_FILE = `${DROPIN_DIR}/sandbox-paths.conf`;

function readList(): string[] {
  if (!existsSync(LIST_FILE)) return [];
  return readFileSync(LIST_FILE, 'utf8')
    .split('\n')
    .map(l => l.trim())
    .filter(l => l && !l.startsWith('#'));
}

function writeList(paths: string[]): void {
  const dedup = [...new Set(paths.map(stripTrailingSlashes).filter(p => p.startsWith('/')))];
  const content = [
    '# Managed by `ritsu path` — modify with `ritsu path add|remove`.',
    '# One absolute path per line. Each is appended to ritsu.service\'s',
    '# ReadWritePaths via the auto-generated drop-in.',
    '',
    ...dedup,
  ].join('\n') + '\n';
  mkdirSync('/etc/ritsu', { recursive: true });
  writeFileSync(LIST_FILE, content, { mode: 0o644 });
}

function regenerateDropIn(): void {
  const paths = readList();
  mkdirSync(DROPIN_DIR, { recursive: true });
  if (paths.length === 0) {
    if (existsSync(DROPIN_FILE)) {
      spawnSync('rm', ['-f', DROPIN_FILE]);
    }
    return;
  }
  const afterUnits: string[] = [];
  for (const p of paths) {
    const u = mountUnitFor(p);
    if (u) afterUnits.push(u);
  }
  const lines = [
    '# AUTO-GENERATED by `ritsu path`. Do not edit by hand.',
    `# Source list: ${LIST_FILE}`,
    '',
  ];
  if (afterUnits.length > 0) {
    lines.push(
      '[Unit]',
      `After=${afterUnits.join(' ')}`,
      `Requires=${afterUnits.join(' ')}`,
      '',
    );
  }
  lines.push(
    '[Service]',
    `ReadWritePaths=${paths.join(' ')}`,
  );
  writeFileSync(DROPIN_FILE, lines.join('\n') + '\n', { mode: 0o644 });
}

function applyChanges(): void {
  regenerateDropIn();
  daemonReload();
  restartService();
}

async function cmdAdd(ctx: CommandContext): Promise<number> {
  const target = ctx.positional[0];
  if (!target) { console.error('usage: ritsu path add <absolute-path>'); return 2; }
  if (!target.startsWith('/')) { console.error('path must be absolute'); return 2; }
  const current = readList();
  if (current.includes(stripTrailingSlashes(target))) {
    console.log(`already present: ${target}`);
    return 0;
  }
  writeList([...current, target]);
  applyChanges();
  console.log(`added: ${target}`);
  return 0;
}

async function cmdRemove(ctx: CommandContext): Promise<number> {
  const target = ctx.positional[0];
  if (!target) { console.error('usage: ritsu path remove <absolute-path>'); return 2; }
  const t = stripTrailingSlashes(target);
  const current = readList();
  if (!current.includes(t)) {
    console.log(`not present: ${target}`);
    return 0;
  }
  writeList(current.filter(p => p !== t));
  applyChanges();
  console.log(`removed: ${target}`);
  return 0;
}

interface PathInfo {
  path: string;
  kind: 'default' | 'extra';
  status: 'mounted' | 'exists' | 'missing';
  mount_unit: string | null;
  perms: string | null;
  owner: string | null;
}

function inspectPath(path: string, extras: Set<string>): PathInfo {
  const unit = mountUnitFor(path);
  const isMount = spawnSync('mountpoint', ['-q', path]).status === 0;
  let status: PathInfo['status'] = 'missing';
  let perms: string | null = null;
  let owner: string | null = null;
  if (existsSync(path)) {
    status = isMount ? 'mounted' : 'exists';
    try {
      const st = statSync(path);
      perms = (st.mode & 0o777).toString(8).padStart(4, '0');
      const lookup = spawnSync('stat', ['-c', '%U:%G', path], { encoding: 'utf8' });
      owner = lookup.status === 0 ? lookup.stdout.trim() : `${st.uid}:${st.gid}`;
    } catch { /* best-effort */ }
  }
  return {
    path,
    kind: extras.has(path) ? 'extra' : 'default',
    status,
    mount_unit: unit,
    perms,
    owner,
  };
}

async function cmdList(ctx: CommandContext): Promise<number> {
  // Authoritative effective list comes from systemd itself — it merges the
  // base unit's ReadWritePaths with every drop-in. The CLI-managed extras
  // live in sandbox-paths.list; the effective set may include other
  // drop-ins or the base unit's defaults too. Show all of it, annotated.
  const extras = new Set(readList());
  const show = spawnSync('systemctl', ['show', SERVICE_NAME, '-p', 'ReadWritePaths', '--value'], {
    encoding: 'utf8',
  });
  const effective = show.status === 0
    ? show.stdout.trim().split(/\s+/).filter(Boolean)
    : [];

  const infos = effective.map(p => inspectPath(p, extras));

  if (ctx.flags.json) {
    console.log(JSON.stringify({ paths: infos, extras: [...extras] }, null, 2));
    return 0;
  }

  if (effective.length === 0) {
    console.log('(could not read ReadWritePaths from systemd — is the service installed?)');
    return 1;
  }

  // Render as columnar table.
  const header = ['PATH', 'KIND', 'STATUS', 'OWNER', 'MODE', 'MOUNT UNIT'];
  const rows = infos.map(i => [
    i.path,
    i.kind,
    i.status,
    i.owner ?? '—',
    i.perms ?? '—',
    i.mount_unit ?? '—',
  ]);
  const widths = header.map((h, c) => Math.max(h.length, ...rows.map(r => r[c].length)));
  const renderRow = (r: string[]): string =>
    '  ' + r.map((cell, c) => cell.padEnd(widths[c])).join('  ');
  console.log(renderRow(header));
  console.log(renderRow(widths.map(w => '─'.repeat(w))));
  for (const r of rows) console.log(renderRow(r));

  if (extras.size === 0) {
    console.log('');
    console.log('  (no extras yet — add with `ritsu path add <abs-path>`)');
  }
  return 0;
}

export const pathCommand: Command = {
  name: 'path',
  summary: 'manage extra filesystem paths the sandbox lets ritsu write to',
  needsRoot: true,
  help: () => [
    'ritsu path — manage extra ReadWritePaths',
    '',
    '  ritsu path add <abs-path>      grant ritsu write access to <abs-path>',
    '  ritsu path remove <abs-path>   revoke access',
    '  ritsu path list                show current extras',
    '',
    'Mechanism: writes /etc/ritsu/sandbox-paths.list (one path per line)',
    'and regenerates /etc/systemd/system/ritsu.service.d/sandbox-paths.conf.',
    'add/remove daemon-reload + restart the service. Idempotent.',
    '',
    'For paths backed by a systemd mount unit, the drop-in also adds',
    'Requires= so ritsu fails fast if the share goes offline.',
  ].join('\n'),
  run: async (ctx) => {
    switch (ctx.subcommand) {
      case 'add':    return cmdAdd(ctx);
      case 'remove': return cmdRemove(ctx);
      case 'list':   return cmdList(ctx);
      case null:     return cmdList(ctx);
      default:
        console.error(`unknown subcommand: ${ctx.subcommand}`);
        return 2;
    }
  },
};
